### ISSUE TITLE
Easier Amount creation

### ISSUE THREAD

**Issue by AureliaDolo** [AurelienFT/massa-auto-rebuy#1]
Here https://github.com/AurelienFT/massa-auto-rebuy/blob/d566ac6eb37117653e6d97d3289b89e992513fe5/src/main.rs#L23 you can use from_string instead of from_raw it takes care of the AMOUNT_DECIMAL_FACTOR for you.

**Comment by AurelienFT** [comment]
Ah ok that's why when I was using from_string with this amount it give me the error that the amount was too big because I don't have to put all decimals. It could worth a documentation on that in massa (or at least an example in the doc)

**Comment by AurelienFT** [comment]
Fixed : https://github.com/AurelienFT/massa-auto-rebuy/commit/a0dec30ba097248ad55a61a9e564066c647f2de9

**Comment by AureliaDolo** [comment]
If you have any more questions on that https://github.com/massalabs/massa/issues/2289
