### ISSUE TITLE
Reference a specific tag

### ISSUE THREAD

**Issue by AureliaDolo** [AurelienFT/massa-auto-rebuy#3]
https://github.com/AurelienFT/massa-auto-rebuy/blob/d566ac6eb37117653e6d97d3289b89e992513fe5/Cargo.toml#L9-L11

You should reference a specific tag (like the latest testnet https://github.com/massalabs/massa/releases/tag/TEST.7.0) and keep it up to date when needed, as there is no guarantee that the data structure in main are the same as in the testnet

**Comment by AurelienFT** [comment]
Thank you ! Fixed : https://github.com/AurelienFT/massa-auto-rebuy/commit/913ffb041664cbacc96631abff40da58d9f39b4a
